org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.vfs.watch=false

minecraft_version=1.21.1
neo_version=21.1.248
moddev_version=2.0.141

mod_id=skylore_islands
mod_name=Skylore Islands
mod_license=MIT
mod_version=1.0.65
mod_group_id=com.skylore.islands
mod_authors=AOE
mod_description=Transforms the Overworld into an expansive realm of floating sky islands with variable altitudes, distant spacing, all biomes, and universal mod structure support.
